doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '5.7'
    charset: utf8mb4
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      datetime_functions:
        UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
        NOW: DoctrineExtensions\Query\Mysql\Now
        DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
        FROM_UNIXTIME: DoctrineExtensions\Query\Mysql\FromUnixtime
      string_functions:
        MATCH: DoctrineExtensions\Query\Mysql\MatchAgainst
        GREATEST: DoctrineExtensions\Query\Mysql\Greatest
        COLLATE: DoctrineExtensions\Query\Mysql\Collate