# config/packages/mailers.yaml
framework:
  mailer:
    #dsn: 'smtp://noreplyfresh@nbk.com.lb:Albarid@rayan123@mail.nbk.com.lb:587?encryption=tls&auth_mode=login'
    dsn: 'smtp://monitoring@suyool.com:3Dg^T146I=c(@smtp.office365.com:587?encryption=tls&auth_mode=login'
